name: Build Subspaced Binary
on:
  push:
    branches: [ "main" ]
    paths:
      - 'daemon/subspaced/**'
      - '.github/workflows/build-subspaced-binary.yaml'
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'daemon/subspaced/**'
      - '.github/workflows/build-subspaced-binary.yaml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      # Check code formatting
      - name: Check code format
        working-directory: daemon/subspaced
        run: cargo fmt -- --check

      # Install system dependencies that were in your Dockerfile
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libdbus-1-dev \
            libxcb1-dev \
            libx11-dev \
            libxi-dev \
            libxext-dev \
            libxtst-dev \
            libxdo-dev

      # Cache Cargo artifacts
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            daemon/subspaced/target
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('daemon/subspaced/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      # Build and test directly with cargo
      - name: Build binary
        working-directory: daemon/subspaced
        run: cargo build --release

      - name: Run tests
        working-directory: daemon/subspaced
        run: cargo test --no-build

      # Upload artifacts and create release remain the same
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: subspaced-linux-x86_64
          path: daemon/subspaced/target/release/subspaced

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: daemon/subspaced/target/release/subspaced
          generate_release_notes: true