name: Build Cuse Synapse
on:
  push:
    branches: [ "main" ]
    paths:
      - 'cuse-synapse/**'
      - '.github/workflows/build-cuse-synapse.yaml'
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'cuse-synapse/**'
      - '.github/workflows/build-cuse-synapse.yaml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CUSE_SYNAPSE_DIR: cuse-synapse


jobs:
  build-linux:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      # Check code formatting
      - name: Check code format
        working-directory: ${{ env.CUSE_SYNAPSE_DIR }}
        run: cargo fmt -- --check

      # Install system dependencies
      - name: Install dependencies

        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libdbus-1-dev \
            libxcb1-dev \
            libx11-dev \
            libxi-dev \
            libxext-dev \
            libxtst-dev \
            libxdo-dev

      # Build and test directly with cargo
      - name: Build binary  
        working-directory: ${{ env.CUSE_SYNAPSE_DIR }}
        run: cargo build --release



      - name: Run tests
        working-directory: ${{ env.CUSE_SYNAPSE_DIR }}
        run: cargo test --release


      # Upload artifacts and create release remain the same
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: cuse-synapse-linux-x86_64
          path: ${{ env.CUSE_SYNAPSE_DIR }}/target/release/cuse-synapse


      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.CUSE_SYNAPSE_DIR }}/target/release/cuse-synapse
          generate_release_notes: true