name: Python Lint

on:
  workflow_call:
  push:


    branches: [ "main" ]
    paths:
      - 'valk/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - '.github/workflows/python-lint.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'valk/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - '.github/workflows/python-lint.yaml'



jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Check formatting with Ruff
        run: uvx ruff format --check .
      - name: Run Ruff linting
        run: uvx ruff check .