name: Ruff Lint and Format

on:
  push:
    branches: [ "main" ]
    paths:
      - 'computeruse/**'
      - '.github/workflows/ruff.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'computeruse/**'
      - '.github/workflows/ruff.yaml'


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Check formatting with Ruff
        run: ruff format --check .

      - name: Run Ruff linting
        run: ruff check .