name: Test Python

on:
  workflow_call:
  push:
    branches: [ "main" ]
    paths:
      - 'valk/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - '.github/workflows/test-python.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'valk/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - '.github/workflows/test-python.yaml'


jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.12']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group=tests
      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen pytest -v
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Check formatting with Ruff
        run: uvx ruff format --check .
      - name: Run Ruff linting
        run: uvx ruff check .